# -*- coding: utf-8 -*-
"""Kopia notatnika AdamByrski.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gie7I8HcUbngBS0mlW0S5_92qRe65Wo_
"""

#Hasło składające się z 8-12 znaków (litery, cyfry i znaki interpunkcyjne)generowane przy pomocy funkcji "secrets"

import secrets
import string

znaki = string.ascii_letters + string.digits + string.punctuation
password = ''.join(secrets.choice(znaki) for i in range(randint(8, 12)))
print("Nowe hasło: "+password)

#Test1
import string
import random

def pw_gen(size = 8, chars=string.ascii_letters + string.digits + string.punctuation):
	return ''.join(random.choice(chars) for _ in range(size))

print(pw_gen(int(input('Podaj długość hasła (liczba)'))))

#Test2
import string
from random import *
characters = string.ascii_letters + string.punctuation  + string.digits
password =  "".join(choice(characters) for x in range(randint(8, 12)))
print (password)